### PR TITLE
Add support for smart quotes and update Slackbot response

### PR DESCRIPTION
**Pull request by josiahwiebe**
I set this up for my work Slack using the Deploy to Heroku button, but was having trouble getting it to work. I realised that my standard double quotes were turning into smart quotes, which was throwing an error. 

I created a regex to filter out smart quotes and replace them with standard quotes. Not sure if you're accepting PRs, but here it is anyway!

### CODE REVIEW

**Comment by josiahwiebe** [comment]
Shoot! I just realised you've already updated the message format.

**Comment by gozman** [comment]
This is a nice fix though, I got burned by the smart quotes feature myself.

**Comment by edchan77** [comment]
I change the quotes to use the | delimiter instead :)
I merged your other stuff otherwise!

**Comment by josiahwiebe** [comment]
I saw that, good call! :) Thanks for merging though, glad I could contribute a bit!

**Pull request merged**
